dist: xenial
env:
  global:
    secure: ueqfSSSdjmBu07u+tUywrOiBwqmf+XoIW3Q2RMx36jeyZd1CLpGAOdRiXXQ/3K2a9YztrQRRlBPHEeJrWLKmRq/QAXhAjAe8Vn0a6XiB1TwUGKXrr3g6tu7838ZWwyCaoedkPqY+KeBBaqcsLQjoxfLtuvMfkt0ldehMHY1mlh3gDV9y77f/XiIqMek5YSuMFJzpXFtVyoVJzQhQoeD9p6fDxXsOXVeInTFbDE3CXX6ti2UQ0CsIqxH6bkdhY/Vmk3B7O6ocIRbMQXxl39r16ebBZ2ijL9YCtsi1hrZ9D3mjk1+jliF5lIqK1zS6at8EoYmHbIOCFZakSGDJ1rdp6HmEnz2T9cOB45hm0BzDy0Q36+wgjCXTG/M/2vhRQqHTZdWaZE9gMUyGYzHm90o9EAW7QdX/lhuEXZ3M4ffbzmziUM/+lBt1/0KUN4LoAIV1iiWWDZQPqKh+TX+gRMUXcHuvEsgz0sxOdIVEyP3U5NIJ0EwnC7bjJ4umMnRq2wiBoyOJ7ouy+O+r64+cw52ERypdK/Qe3RUGz2FmrVVwWFBjY7ivOQHAHPmRKXaboej5FZD4qpMCpOgYxan1FHgNPceIeT7qq35x21HRYAbn5w7qxSqAS+MmWHRF75AVZfZ8llNTKgHHlj2PHztNAi1uL3q18drk+Xm2tiUSXIwhXHY=
language: python
python:
- '3.7'
install:
- cp contrib/env-sample .env
- pip install -r requirements.txt
- pip install coverage
before_script:
- python manage.py migrate --noinput
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
script:
- coverage run manage.py test
after_script:
- coverage xml
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
